name: CI Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python_version}}
      - name: Run Unit Tests
        run: |
          pip install -r ./requirements/base.txt
          pip install -U pytest pytest-cov codecov pycodestyle flake8
          pytest tests/ --cov=./mvlearn/ --ignore=tests/multiviewica --ignore=tests/torch --ignore=tests/graspy
          pip install -r ./requirements/multiviewica.txt
          pytest tests/multiviewica/ --cov=./mvlearn/ --cov-append
          pip install -r ./requirements/torch.txt
          pytest tests/torch/ --cov=./mvlearn/ --cov-append
      - name: Check code formatting
        run: |
          pycodestyle mvlearn/
          flake8 mvlearn
          flake8 examples
